name: Build

on: 
  workflow_dispatch:
  push:
  release:
    types: [published]
  pull_request:
    branches:
    - master

jobs:
    build:
      name: Build
      env:
        NUPKG_MAJOR: 0.999
        CODESIGN_PFX: ${{ secrets.CODESIGN_PFX }}
      runs-on: windows-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 8.0.x Preview
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true
          
      - name: Build
        shell: pwsh
        run: |
          $VERSION="$env:NUPKG_MAJOR-ci$env:GITHUB_RUN_ID"
          if ($env:GITHUB_EVENT_NAME -eq "release") {
            $VERSION = $env:GITHUB_REF.Substring($env:GITHUB_REF.LastIndexOf('/') + 1)
          }
          echo "::set-output name=pkgverci::$VERSION"
          echo "PACKAGE VERSION: $VERSION"
          
          New-Item -ItemType Directory -Force -Path ./artifacts
          New-Item -ItemType Directory -Force -Path ./output

          $pfxPath = Join-Path -Path $pwd -ChildPath "codesigncert.pfx"
          [IO.File]::WriteAllBytes($pfxPath,[System.Convert]::FromBase64String($env:CODESIGN_PFX))

          dotnet build --configuration Release ./MauiCheck.sln
          dotnet pack --output ./artifacts -p:PackageVersion=$VERSION -p:SigningCertificatePfxFile=$pfxPath --configuration Release ./MauiCheck/MauiCheck.csproj
          dotnet nuget sign .\artifacts\*.nupkg --certificate-path $pfxPath --timestamper http://timestamp.entrust.net/TSS/RFC3161sha2TS

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: NuGet
          path: ./artifacts

    publish:
      name: Publish
      needs:
        - build
      runs-on: windows-latest
      steps:
        - name: Download Artifacts
          uses: actions/download-artifact@v1
          with:
            name: NuGet

        - name: Push NuGet
          if: github.event_name == 'release'
          run: |
            dotnet nuget push NuGet\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_ORG_API_KEY }} --skip-duplicate
