name: Build

on: 
  workflow_dispatch:
  push:
  release:
    types: [published]
  pull_request:
    branches:
    - master

jobs:
    build:
      name: Build
      env:
        NUPKG_MAJOR: 0.999
        CODESIGN_PFX: ${{ secrets.CODESIGN_PFX }}
        APPLE_CERT_CN: ${{ secrets.APPLE_CERT_CN }}

      runs-on: windows-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 8.0.x Preview
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true
          
      - name: Build
        shell: pwsh
        run: |
          $VERSION="$env:NUPKG_MAJOR-ci$env:GITHUB_RUN_ID"
          if ($env:GITHUB_EVENT_NAME -eq "release") {
            $VERSION = $env:GITHUB_REF.Substring($env:GITHUB_REF.LastIndexOf('/') + 1)
          }
          echo "::set-output name=pkgverci::$VERSION"
          echo "PACKAGE VERSION: $VERSION"
          
          New-Item -ItemType Directory -Force -Path ./artifacts
          New-Item -ItemType Directory -Force -Path ./output

          $pfxPath = Join-Path -Path $pwd -ChildPath "codesigncert.pfx"
          [IO.File]::WriteAllBytes($pfxPath,[System.Convert]::FromBase64String($env:CODESIGN_PFX))

          dotnet build --configuration Release ./MauiCheck.sln
          dotnet pack --output ./artifacts -p:PackageVersion=$VERSION -p:SigningCertificatePfxFile=$pfxPath --configuration Release ./MauiCheck/MauiCheck.csproj

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: NuGet
          path: ./artifacts


    maccodesign:
      runs-on: macos-latest
      name: Mac Signing
      needs:
        - build
      steps:
        - name: Download Artifacts
          uses: actions/download-artifact@v1
          with:
            name: NuGet

        - name: Import Apple Cert
          uses: apple-actions/import-codesign-certs@v2
          with: 
            p12-file-base64: ${{ secrets.APPLE_CERT }}
            p12-password: ${{ secrets.APPLE_CERT_PWD }}
  
        - name: Sign and Repackage
          shell: pwsh
          run: |
            dotnet tool install -g nupkgwrench
            nupkgwrench extract ./NuGet/*.nupkg --output ./tmp

            security find-identity -p codesigning ~/Library/Keychains/signing_temp.keychain-db

            codesign --sign "$env:APPLE_CERT_CN" "$pwd/tmp/**/maui-check" --keychain ~/Library/Keychains/signing_temp.keychain-db

            New-Item -ItemType Directory -Force -Path ./NuGetSigned
            nupkgwrench compress ./tmp --output ./NuGetSigned/
            $pfxPath = Join-Path -Path $pwd -ChildPath "codesigncert.pfx"
            [IO.File]::WriteAllBytes($pfxPath,[System.Convert]::FromBase64String($env:CODESIGN_PFX))
            dotnet nuget sign ./NuGetSigned/*.nupkg --certificate-path $pfxPath --timestamper http://timestamp.entrust.net/TSS/RFC3161sha2TS

        - name: Upload Artifacts
          uses: actions/upload-artifact@v1
          with:
            name: NuGetSigned
            path: ./NuGetSigned

    publish:
      name: Publish
      needs:
        - maccodesign
      runs-on: windows-latest
      steps:
        - name: Download Artifacts
          uses: actions/download-artifact@v1
          with:
            name: NuGetSigned

        - name: Push NuGet
          if: github.event_name == 'release'
          run: |
            dotnet nuget push NuGetSigned\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_ORG_API_KEY }} --skip-duplicate
